### ISSUE TITLE
Read the entire commit message, not just the first line

### ISSUE THREAD

**Issue by darinmorrison** [autosuite/autoskip#4]
I've forked this action and tried to use it as described in the README:

```yaml
jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: interfaces-rs/skip-commit@master
        with:
          commit-filter: skip-ci
          always-allow-tags: true
          ref: ${{ github.ref }}
```

I've tried to test the action with a commit with a message like so:

```
Some commit message.

[skip-ci]
```

However, the action doesn't seem to trigger. I've also tried just with `skip-ci` without the enclosing square brackets.

Am I missing something? It might help to see a complete example with a known working filter and triggering message.

Anyway, thanks for making this!
